# THE ANSWER:
# The outlier ruins the linear fit, and way-to-go data analyst answer would be excluding the outlier
# and therefor change Y_outlier to Y_h on line 16 and use this fit, or implementing q-norm(line 83). However, what 
# if the outlier was an important, non-removable part of data? My best guess was multi-sinusoidal function, that 
# fits pretty well and weights are determained nicely using OLS. LLM suggested Gaussian RBF, which also works, however, 
# I prefer my sinusoidal method more. With such a low amount of data, it is hard to tell whether sinusoidal fits closely to
# the "real" function, since we don't know what's "actually" between 2 points and whether it oscilates properly.

     
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import copy

X_h = np.random.uniform(0,3,size=(10,1))             #generate a bunch of randomly selected X's
Y_h = 5*(X_h) + np.random.normal(0,1,size=(10,1))   #Y = 2x + noise

Y_outlier = copy.copy(Y_h)                           #create a copy of the original Y vector 
Y_outlier[6] = 50.0                                 #the new outlier value is much larger than the rest

w = (1.0/np.dot(X_h.T, X_h))[0,0]*X_h.T.dot(Y_outlier)[0,0] 
plt.plot(np.arange(np.min(X_h),np.max(X_h),0.1), w*np.arange(np.min(X_h),np.max(X_h),0.1), color="orange", lw=3)

plt.title("Data generated by a linear function with an outlier")
plt.scatter(X_h, Y_outlier, color="red")
plt.scatter(X_h, Y_h, color="blue")
plt.show()

def sinusoid_basis(x, K):                 #basis functions [1, sin(x), cos(x), sin(2x), cos(2x), ...]
    cols = [np.ones_like(x)]
    for k in range(1, K+1):
        cols.append(np.sin(k*x))
        cols.append(np.cos(k*x))
    return np.hstack(cols)

K = 20                              #number of harmonics -> 2K+1 weights
Phi = sinusoid_basis(X_h, K)
w_next = np.random.normal(0,1,size=(2*K+1,1))
step_size = 0.01

i = 0
max_iter = 100000

while i < max_iter:
    w_next -= step_size*2*Phi.T.dot(Phi.dot(w_next) - Y_outlier)
    i += 1

x_line = np.arange(np.min(X_h),np.max(X_h),0.01).reshape(-1,1)
plt.plot(x_line, sinusoid_basis(x_line, K).dot(w_next), color="orange", lw=3)
plt.title("Regression with multi-sinusoidal basis, weights determined by gradient descent")
plt.scatter(X_h, Y_outlier, color="red")
plt.scatter(X_h, Y_h, color="blue")
for xi, yi in zip(X_h[:,0], Y_outlier[:,0]):
    plt.annotate(f"{xi:.2f}", (xi, yi), textcoords="offset points", xytext=(5,5), fontsize=8)
plt.show()

def gaussian_basis(x, centers, s):        #basis functions [1, exp(-(x-c)^2/2s^2) for each center c]
    cols = [np.ones_like(x)]
    for c in centers:
        cols.append(np.exp(-np.power(x - c, 2)/(2*s**2)))
    return np.hstack(cols)

centers = np.linspace(0, 3, 10)           #bump centers spread over the data range -> 11 weights
s = 0.3                                   #bump width: each basis function only acts locally
Phi_g = gaussian_basis(X_h, centers, s)
w_g = np.random.normal(0,1,size=(len(centers)+1,1))
step_size = 0.01

i = 0
while i < max_iter:
    w_g -= step_size*2*Phi_g.T.dot(Phi_g.dot(w_g) - Y_outlier)
    i += 1

plt.plot(x_line, gaussian_basis(x_line, centers, s).dot(w_g), color="orange", lw=3)
plt.title("Regression with Gaussian RBF basis, weights determined by gradient descent")
plt.scatter(X_h, Y_outlier, color="red")
plt.scatter(X_h, Y_h, color="blue")
for xi, yi in zip(X_h[:,0], Y_outlier[:,0]):
    plt.annotate(f"{xi:.2f}", (xi, yi), textcoords="offset points", xytext=(5,5), fontsize=8)
plt.show()


q = 1.1
w_q = np.random.normal(0,1,size=(1,1))
step_size = 0.001

i = 0
while i < max_iter:
    r = Y_outlier - X_h.dot(w_q)
    w_q += step_size*q*X_h.T.dot(np.power(np.abs(r), q-1)*np.sign(r))
    i += 1

w_clean = (1.0/np.dot(X_h.T, X_h))[0,0]*X_h.T.dot(Y_h)[0,0]   #OLS on clean data, for reference
print(f"OLS slope with outlier:  {w:.3f}")
print(f"OLS slope on clean data: {w_clean:.3f}")
print(f"q-norm (q={q}) slope:    {w_q[0,0]:.3f}   (true slope = 5)")

plt.plot(x_line, w*x_line, color="orange", lw=3, label=f"OLS (2-norm) with outlier: w={w:.2f}")
plt.plot(x_line, x_line.dot(w_q), color="green", lw=3, label=f"q-norm, q={q}: w={w_q[0,0]:.2f}")
plt.plot(x_line, w_clean*x_line, color="gray", ls="--", lw=2, label=f"OLS on clean data: w={w_clean:.2f}")
plt.title("Robust linear regression with q-norm loss, weight determined by gradient descent")
plt.scatter(X_h, Y_outlier, color="red")
plt.scatter(X_h, Y_h, color="blue")
plt.legend()
plt.show()